options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Etapa 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'painel-admin'  # 👉 aqui muda para a pasta do painel-admin
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/admin-panel', '.']

  # Etapa 2: Push da imagem
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/admin-panel']

  # Etapa 3: Deploy seguro no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - admin-panel  # 👉 nome do serviço novo no Cloud Run
      - --image=gcr.io/$PROJECT_ID/admin-panel
      - --region=southamerica-east1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}
      - --set-env-vars=DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},DB_HOST=${_DB_HOST},ADMIN_EMAIL=${_ADMIN_EMAIL},ADMIN_PASSWORD=${_ADMIN_PASSWORD},COOKIE_SECRET=${_COOKIE_SECRET},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},COOKIE_SECRET=${_COOKIE_SECRET},BASE_URL=${_BASE_URL}
      - --set-secrets=DB_PASSWORD=DB_PASSWORD_SECRET:latest
      - --timeout=900s
