options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Etapa 1: Build da imagem
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-cdc', '.']

  # Etapa 2: Push da imagem
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-cdc']

  # Etapa 3: Deploy com tratamento especial para a senha
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        # Usando aspas simples para evitar interpretação de caracteres especiais
        gcloud run deploy backend-cdc \
          --image gcr.io/$PROJECT_ID/backend-cdc \
          --region southamerica-east1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances ${_INSTANCE_CONNECTION_NAME} \
          --set-env-vars='NODE_ENV=${_NODE_ENV},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME},DB_HOST=${_DB_HOST}' \
          --timeout=900s