# swagger: '2.0'
# info:
#   title: CDC Public Gateway
#   description: Gateway público para expor rotas do Cloud Run
#   version: 1.0.0

# x-google-backend:
#   address: https://backend-cdc-427143287446.southamerica-east1.run.app
#   protocol: h2
#   jwt_audience: https://backend-cdc-427143287446.southamerica-east1.run.app

# paths:
#   /{path=**}:
#     get:
#       summary: Proxy GET para qualquer rota
#       operationId: proxyGET
#       parameters:
#         - name: path
#           in: path
#           required: true
#           type: string
#       responses:
#         '200':
#           description: OK
#     post:
#       summary: Proxy POST para qualquer rota
#       operationId: proxyPOST
#       parameters:
#         - name: path
#           in: path
#           required: true
#           type: string
#       responses:
#         '200':
#           description: OK

swagger: '2.0'
info:
  title: CDC Public Gateway
  description: Gateway público para expor rotas do Cloud Run
  version: 1.0.0

x-google-backend:
  address: https://backend-cdc-427143287446.southamerica-east1.run.app
  protocol: h2
  jwt_audience: https://backend-cdc-427143287446.southamerica-east1.run.app

paths:
  /{path=**}:
    options:
      summary: Handle CORS preflight requests
      operationId: corsPreflight
      responses:
        '204':
          description: Successful CORS preflight
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Max-Age:
              type: string
      x-google-backend:
        address: https://backend-cdc-427143287446.southamerica-east1.run.app
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
    get:
      summary: Proxy GET para qualquer rota
      operationId: proxyGET
      parameters:
        - name: path
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              type: string
    post:
      summary: Proxy POST para qualquer rota
      operationId: proxyPOST
      parameters:
        - name: path
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              type: string